[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
balance = "3djk52LyU2aGaeZCddjBWgo1dx1Z2o4HAVw3patvHWNi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
