[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
init_if_needed = "BryuGUGr6sYHmG7w6BmLmTCM7kmZjNKRXXEDWkiahUAP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
