[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
rent = "DT7Bxyyx24bbiNvmSuC9EZ1Z9SxFPbjzSyC3xnGYnPVc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
