[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sender = "J6pdvTB4EBfXGYHVsJdRmLXi9K8B4bwUDd5T8y9oAUBH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
