[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
data_reader = "Bav1fsb6K3XqhZ6W2Vj4vs5G1tPyjCfLE3FPYpFrRFKn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
