[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
other_write = "26Kiu5LSV5xXDN3yGwE8L6aU59kKRKdyyKtSQv5Vu5VC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yijingguo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
